sudo: required

language: go

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: K7gizHZDz+XqrNHlT2v7kGI/lLkmB+QDCRHkbo/AIYokOCaF+bAc+vd4HE1EkhFH8jliXJZlpMCVdnaV35WZNO35AGLa03I1xhJg/qNlzI1SYzzVlLlOIBwv5pbek4JI9aqIs5Jx0SzU28W6mmtRuAUZ/two4sWp8TRqNz0wgI8+JU/QPiVnXdCbgEmJw+nY88fvFv55x2lYqO4tdRlKAHZ4y0zC+RmKbj6UWJEh6YMgXn0PWfFpKfSSrbakg3m1TMEWPhF0y+yPX/sPt2fNF/QsHIxPVdTpM+duurxMIFKYhkx0SBPFMmW0MNh4kvHwNwWjwIn9v7uXNkrWR1HIsgppaJbzIYXCD7I9je1yNaBZXO8h6tOTH+inZOR9t0lnrJWJrIBwy3cQYMSqhRxhPfArbcgE3ulxwmf9F/tX5xEjIF57FRF9Ai9Jju914ZnNIMDpW2HS/14lpt9VC2OOFWARNAhqYo+yx3cX8bJTu/shx7dme3s6+zAeFZ5ZTbSqiCdHlxDFZRIHDQsskowV71RT/76J9/kr/0inANNw9CZNTB5YnTwYnO2CWW2cLLd5wY/LEJgZ0SQ1TbtmX78zbHP5Rk4yS72jtr/y6Bu+gVXpT2C5/rxHsVMa3lzUuChZEGKaMoTGWNIH0KrNXs+EAek7SR9Cfh9r9KPL0MRa/B4=  # DOCKER_EMAIL
    - secure: W8DFocKZfTzr9lFlmqmdLLzNKvbfidXQBE+PXTl2Yk0EZSXTaZ1/JYvZMJei5xAOo25eQjYqP+UrsSWOc/0I7yeMcxXmYwOgQ9uEwI9v9uerpWjW5QkxKupBaoUo71Toz7wF8WAor/QzTZd56henqutCcI88kH/7kznwYq6yUXqKI8ndadpiP0kRK6Xxh2BBSyQ65mJhHU61SYlfFY2Y3bmwTQJ03t9HnQdgqBa6i2SuTTZ3QuZPDqbx12xX0RfeZT+ImkyC8HL0z+YluKoPwvXVh+9dv5fQW3kOrfZY80qTfGPb9lNWwSoaE+LTxmdnwwFChybGoN9z4NpUY4JfWac6IA1nKACG1esgmGX5xLTpYiMScnblV0NTQ+3KqyejqAftrbP35ha8EXN2eNPJioh4focdnGOBXWUsA8W1WX+19Wtl63VAN6SLS+GGBzpiQBR5qHv5/rdIVmEKrc8KPXfZCLMzlEepYJ947EoV1xow4a+2n7uA62iMrNWyMGP5SVchXYVNTtBdrvwUUdgmo9wQpKHaT411FkAUsiWZ0J5M3VbDuVovq8RedkreBDG7pFVdoT/C97FSVpUsgRdKxf4tdlMmaMlbVlM1Dhq8Gk3f7NMAHyYq0TdLKuvbV3HR7tMDCYQVjWARb5tGgiRAcAcL/tk2kkAHsX7rPb3qfJM=  # DOCKER_USER
    - secure: Kj5LqbCTAGfi9jzeKBqc/EwoT0kt/SiN2X5tVqKed6H60WTYx2WacPWtj3J7VQbyeP4ViGNQsLNiiLIM2rccho2evzAXpPYYpidzklUpMiacYwZrmMCgkpjmzYVcIaEh3UIs+bVUOLBxV+1d/h2BZU/0CAVu5eZI9CNVaj/h2A/hN783tlQ1/OSw6cbuyhLldWZgdF0lhL9YBiu1iqvESqO+EPHNfjw8NhnZQmmgjQzHOFj9+LxZzq86kj+NX/lhL++ooMlSzGzRzW8uYH405Y2ERJCHUu5Cis9+E/enoU/h1qW3QpI6dWZtiHlLRorlw/CUtkXz8SNJN2Lb42W9LnaS+MAm+MnszVXZQ4vAc+Y5ylgKoyFRRXMhN6t+kRO//LHeAQOhGz6LiOaMbutuYCKPemdO9WiK3KZ/iCZ0M0eFTOqYbm8T1+d4LQsqB5wUhf3XKQHHcUGSjjFEx/KUtGmhWBWS4ZFvIAruyVnfNycHiquV0AZinqHLbjXPlBLnqSEVaMjwGDqcMJWl4Dr75hJxZM9Jy5r7IB2AelD/6Gd9+YcjKKzHbSZx4rAV61M7MKU+V/e5B5kkxg8k6ULzQA7a6VqfFXb1OkkANAyJ+EqGvJZVXcMykGhGMKllfTl3EocFLddJom+g1c3IR+JRg3jfoqXNV20Co6SoEFeuWmw=  # DOCKER_PASS

install:
  - make install

script:
  - make test
  - make xlang

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=yarpc/xlang
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
