sudo: required

language: go

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - secure: jCNpBS0a7BJDk1oYBXo4T++DJeTbZuQC/sL5PEOcEYtYcx2i1RuMVGo8fyFMHItYVlpkDJPVT2Tou3CyUSsp95YkK2E8yVI6cAGte7uOWt2wqOWe0IzLPB9iI5Tq/LMLmhzOZPoS0juRB151SIvCgwxd7dW65C1ejOAwR/O87TiVJNSEqJ49i4uMJ+kAxua7WhnDvrm5cfJJWrQeBJGx8w5I7f89o09CpYF9bYMEINI/dihSGkP+kHY4/DudezHFBjRhkW5BuBMOxL5878pVfD78KX/5yqLOhtWr3FdUQTryc8Lc0rJ1xDvKT0qRuTy6bZ5d6ej6YNw6liRcasWfrjbgMrs3XJjpBKoFfuwAWR6vKuoPvCnGgnqZQ33gdP8+pCnPj+yd7jjkY6PD6nIA5ASvZ1QHci8W7TOgZ1vlify1opekKiFpD6LnQ+y/8zTZj3xn9BA6fAp37VrTA6WjBDXRrWIHShfWuZrDpt+rKpqLyKOrlpxxlqTbwRLdKiMU2Z8lq7N2Y7/3NYXToe2RAr6z45+QQfI5yQUnon3DltrsgfqNgLjlWrLQZqLoQ/GO/ZqopMCT1pvNTVEaCaZPoICU/oV2c7TZMT6CZj12jnI1oVtynlydPBIpsYLmlVdYb1NbkhBTBQwVn348fxRA8at+xMnpmOwBP4vsb8QgE8A=
    - secure: QUUv+UXZQzsUVvp9UiVSYNq5dGhrYAsLWpZcUxFSjRJmrbInfOKKRhmctb2U6o7Gc1Wc2twP17Gp0zGn8J1lI8XcOEfIHLzElY9Aqa22KSvybL5H4RPoI6lJdKCdfknT1MFFrySSIe2wx6iXhCoQ2ghkgKxPNGZgnnHOyMZwt7iFnfULlcJoqwFhhQYxMf4SWcAjI4Eyknn4al3QPJZJaHeETGG7mr+9QUyJlkwjgxIlPxTIJxV2YP7VsSzbZsocW98MAfwdLgrpULG+P7Fxu5afEQ42wlqL7sLSf1ZgJUDnCoUWKipRtaeXQVmdr2Wi6aeAQxzDr05lhmu1AN65bs7NXdbfdeEONrqoUviAaHEcpOBSAMiWHZIIYlY/EUQARdeqmiZUYgKghLbGo46zo8drqReTqDAZrkbEiKu+XQaGQQXULBInr26Xy0uRstZGr0/8RWhmkYDysp0wHxZ1I6tIDyW0BXaPXEEC3/zp++9Xd7l4uiOBxEX86gut2aENTeVHk4Ktp0kvJ25iUvI0G7JbRb2X2CJunuwQjVMCa/nx4SwJkVWz4+Xxwfuo0TrNS7U4xh6foQdaxa0eVDLQhkFOQt38FjCVW0wZLyH/nz+stsX8pH085hC/EDWbe/FnhDqEodBL9ga3eTTW9RQeZ4m5snDoQq/0/zoLOdS73UU=
    - secure: m0CU88ZGgGx36q4vsf2BcxD04YCcLPgwtdlxNCUG0SI+LkWQevMJLCt9RTYJMd90qfYzpVTSvwwpUfS6eudZ7pqovfVfiQpsmcHCTTQ0MTnb5DGICRLRA9nGjIi9tXUQZTpeazlzCsAvRhtezZmBBzwE2CGzBVyUO7TgdwScSzbjrrTfo9i1GVVpnp4gP9Uv79D5wEADSweKpPrhCvkLWzIc/yN9VJsMHxiShMOkM4QdGQHA7GroFsh0vchdPv8iS2WJCwq9N1kwY9EKgv2epTbrXrJmar3jrkvU2DOgBXuMW3w3rnOlWzPh7Aw+6V8PZ1EPY0kKo1S7fwprXQ7BLTwIK8+ZebhTWMwHlriTzAk/k4MjsarXxK7fMjOyNFCM4dbQTwUjVoD1G51djoYfVUGD1wGskOq63x84zhCUIbFoz+pYdzZVHbSZmwyvEDVOdIi4BlLkGkC3MX1Z0TrXDMc+DUD27pQ/+u4dXHjeixO2RzBfsHGVa3Ehq6WYEk6fO5UqwA1xNKWuwZQvAVQ2eiddDOoLmZ663K959VPbGuzm/hEsiwpbi+7625oNGT31OaUMlaeunomT6sLj/63yQb9J5WcmslizU36Qp3dr+OQdHLC65F/Gb0V2lKI5Oo9XVnQubLd46VlpH3mtxT8qe7B7wj1TBMzmeEV1y0BLHs4=

install:
  - make install

script:
  - make test
  - make xlang

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=yarpc/xlang
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
