xlang:
    build: .
    links:
        - yarpc-go
        - yarpc-java
        - yarpc-python
        - yarpc-node
    environment:
        - XLANG_CLIENTS=yarpc-go,yarpc-java,yarpc-python,yarpc-node
        - XLANG_SERVERS=yarpc-go,yarpc-java,yarpc-python,yarpc-node
        - XLANG_BEHAVIORS=call,not_found

yarpc-go:
    image: breerly/hello-server
    ports:
        - 8080
    environment:
        - HELLO_SLEEP=2

yarpc-java:
    image: breerly/hello-server
    ports:
        - 8080

yarpc-python:
    image: breerly/hello-server
    ports:
        - 8080

yarpc-node:
    image: breerly/hello-server
    ports:
        - 8080
